### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by Magi1053**
Use multistage build to compile the frontend assets and copy it into the app

### CODE REVIEW

**Comment by timothystewart6** [comment]
Hey, thanks!  I think the CI job would need to be updated too

**Comment by Magi1053** [comment]
Yeah probably. I'm new to GH actions but I can take a crack at it

**Comment by timothystewart6** [comment]
Now I think we are building twice, once outside of the `Dockerfile` and one inside

**Comment by timothystewart6** [comment]
This is why I purposely left the nodejs build outside of the `Dockerfile`  :)  I am familiar with multistage builds but when building client side apps I typically do it outside of the `Dockerfile` so that I can take advantage of caching, store cached node modules, and preserve the bundle as an artifact between stages

**Comment by Magi1053** [comment]
Makes sense. I was trying to build it from source and was confused why it wasnt building the frontend too. I did not even factor in the CI aspect.

**Comment by Magi1053** [comment]
Feel free to close if you dont want it

**Comment by timothystewart6** [comment]
Thanks! Let me think about this some more.  I've bumped into this a few times when trying to cache artifacts / build time modules during CI but never found a great way to solve this for multi stage Docker builds.

**Comment by timothystewart6** [comment]
Closing this but will revisit int he future if I find a bettey way

**Pull request closed without merging**
